## Getting started


In [1]:
import torch
print(torch.rand(2, 2))

tensor([[0.0213, 0.6829],
        [0.6280, 0.8221]])


In [3]:
x = torch.tensor([[0,0,1],[1,1,1],[0,0,0]])
x

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [4]:
x[0][0] = 5
x

tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [5]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [10]:
torch.ones(1,2) + torch.ones(1,2)

tensor([[2., 2.]])

In [15]:
x = torch.rand(1)
x

tensor([0.0067])

In [16]:
x.item()

0.006701350212097168

Tensors can live on CPU or GPU abd can be copied:

In [17]:
cpu_tensor = torch.rand(2)
cpu_tensor.device

device(type='cpu')

In [ ]:
gpu_tensor = cpu_tensor.to("cuda")
gpu_tensor.device