## Tensor


In [1]:
import torch
print(torch.rand(2, 2))

tensor([[0.0213, 0.6829],
        [0.6280, 0.8221]])


In [3]:
x = torch.tensor([[0,0,1],[1,1,1],[0,0,0]])
x

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [4]:
x[0][0] = 5
x

tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [5]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [10]:
torch.ones(1,2) + torch.ones(1,2)

tensor([[2., 2.]])

In [15]:
x = torch.rand(1)
x

tensor([0.0067])

In [16]:
x.item()

0.006701350212097168

Tensors can live on CPU or GPU abd can be copied:

In [17]:
cpu_tensor = torch.rand(2)
cpu_tensor.device

device(type='cpu')

In [ ]:
gpu_tensor = cpu_tensor.to("cuda")
gpu_tensor.device

## Tensor Operations

extract max:

In [20]:
t = torch.rand(2, 2)
t

tensor([[0.3445, 0.3720],
        [0.2947, 0.8938]])

In [21]:
t.max()

tensor(0.8938)

In [22]:
t.max().item()

0.8938155174255371

change type:

In [23]:
long_tensor = torch.tensor([[0,0,1],[1,1,1],[0,0,0]])
long_tensor.type()

'torch.LongTensor'

In [25]:
float_tensor = torch.tensor([[0,0,1],[1,1,1],[0,0,0]]).to(dtype=torch.float32)
float_tensor.type()

'torch.FloatTensor'

functions starting with _ change tensor in-place:

In [28]:
random_tensor = torch.rand(2, 2)
print(random_tensor)
print(random_tensor.log2())
print(random_tensor)

tensor([[0.6008, 0.7526],
        [0.1934, 0.6894]])
tensor([[-0.7350, -0.4101],
        [-2.3705, -0.5365]])
tensor([[0.6008, 0.7526],
        [0.1934, 0.6894]])


In [29]:
print(random_tensor.log2_())
print(random_tensor)

tensor([[-0.7350, -0.4101],
        [-2.3705, -0.5365]])
tensor([[-0.7350, -0.4101],
        [-2.3705, -0.5365]])


reshaping for example MNIST (handwritings images) from 784 to 1(grascale) * 28 * 28(pixels):

In [30]:
flat_tensor = torch.rand(784)
view_tensor = flat_tensor.view(1,28,28) # view operates as a view of tensor.
# If the data changes, view also (unless new block of memory is allocated - call .contiguous() to fix)
view_tensor.shape

torch.Size([1, 28, 28])

In [33]:
reshaped_tensor = flat_tensor.reshape(1,28,28) # preffered, as it performs contiguous behind the scenes
reshaped_tensor.shape

torch.Size([1, 28, 28])

rearrange dimensions:

In [34]:
height_width_channel = torch.rand(640, 480, 3)
channel_height_width = height_width_channel.permute(2, 0, 1)
channel_height_width.shape

torch.Size([3, 640, 480])

## Tensor Broadcasting

Broadcasting allows perform operations between a tensor and a smaller tensor. If
- Two dimencions are equal
- One dimencions is 1

In [35]:
torch.ones(2,2) + torch.ones(3,3)

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [36]:
torch.ones(1,3) + torch.ones(3,3)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [39]:
torch.ones(3,3) + torch.ones(1,3)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])